### Numpy
* NumPy is a general-purpose array-processing package. 
* It provides a high-performance multidimensional array object, and tools for working with these arrays. 
* It is the fundamental package for scientific computing with Python

In [2]:
## import the library
import numpy as np

In [3]:
# list to array and shape 
lst=[1,2,3,4]
arr=np.array(lst)
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(4,)


In [4]:
# list to nested array
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr=np.array([lst1,lst2,lst3])
print(arr.shape)
print(arr)

(3, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [5]:
# indexing 
lst=[1,2,3,4]
arr = np.array(lst)
arr[3]

4

In [6]:
# we can change value 
arr[3]=5
print(arr)
print(arr[-1])

[1 2 3 5]
5


In [7]:
# array slicing 
print(arr[:-1])
print(arr[::-3])

[1 2 3]
[5 1]


In [12]:
# make a nasted array 
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr=np.array([lst1,lst2,lst3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [13]:
# find the second column of this array 
arr[:,2]

array([3, 4, 5])

In [21]:
# second row and first 2 column 
arr[1,0:2]

array([[2, 3],
       [3, 4]])

In [23]:
# second and third rows and second column 
arr[1:3,1:2]

array([[3],
       [4]])

In [24]:
# second and third row and forth and fifth column 
arr[1:,3:]

array([[5, 6],
       [6, 7]])

In [29]:
# arr declearation 
lst = [1, 2, 3, 5]
arr = np.array(lst)
arr<2

array([ True, False, False, False])

In [30]:
# see the indexing 
arr[arr<2]

array([1])

In [31]:
# Check the shape of the array
lst = [[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]]
arr = np.array(lst)
arr.shape

(5, 3)

In [32]:
# Reshape the array 
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [44]:
# mechanism to create an array
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [33]:
# create and array and reshape it 
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [34]:
# array multiplication 
lst=[1,2,3,4]
arr = np.array(lst)
arr*arr

array([ 1,  4,  9, 16])

In [35]:
# ones function 
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
# zeros function 
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
# random function
arr = np.random.randint(10,50,4)
arr = arr.reshape(2,2)
print(arr)

[[47 19]
 [42 29]]


In [39]:
np.random.randn(5,5)

array([[ 0.23226493, -0.29728144, -1.56295356, -0.10712198, -1.36223352],
       [ 2.62259787,  1.05117602,  0.53831764, -1.61601827, -0.28178182],
       [-0.45565231, -0.37574884, -1.60936243,  0.41834149, -1.51367451],
       [ 1.44686903, -0.64788844, -1.2040344 ,  0.55307237,  0.20417024],
       [-1.25908475, -0.7267581 ,  0.45885546, -0.71968455, -0.34063447]])

In [80]:
np.random.random_sample((4,7))

array([[0.13871895, 0.58456466, 0.31541441, 0.67910295, 0.1837086 ,
        0.08103746, 0.50976945],
       [0.67483078, 0.41252643, 0.0877961 , 0.92338101, 0.25762097,
        0.55850649, 0.26534539],
       [0.05930126, 0.53209293, 0.90407746, 0.71743787, 0.89905166,
        0.22360872, 0.10365036],
       [0.36820358, 0.30483507, 0.49569278, 0.7850211 , 0.96484935,
        0.72614993, 0.83010606]])