### Pandas
1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

In [1]:
!pip install pandas


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import numpy as np

In [6]:
# create numpy array 
data = np.arange(0,42).reshape(6,7)
print(data)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [7]:
# Create Dataframe
df=pd.DataFrame(data,index=["Row1","Row2","Row3","Row4","Row5","Row6"],
                columns=["Column1","Column2","Column3","Column4","Column5","Column6","Column7"])

In [8]:
df.head(2)

Column1  Column2  Column3  Column4  Column5  Column6  Column7
Row1        0        1        2        3        4        5        6
Row2        7        8        9       10       11       12       13

In [9]:
df.tail(4)

Column1  Column2  Column3  Column4  Column5  Column6  Column7
Row3       14       15       16       17       18       19       20
Row4       21       22       23       24       25       26       27
Row5       28       29       30       31       32       33       34
Row6       35       36       37       38       39       40       41

In [10]:
# Check type
type(df)

pandas.core.frame.DataFrame

In [13]:
# Check info 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Row1 to Row6
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  6 non-null      int32
 1   Column2  6 non-null      int32
 2   Column3  6 non-null      int32
 3   Column4  6 non-null      int32
 4   Column5  6 non-null      int32
 5   Column6  6 non-null      int32
 6   Column7  6 non-null      int32
dtypes: int32(7)
memory usage: 216.0+ bytes


In [14]:
# describe will do statistical analysis of the column data 
df.describe()

Column1    Column2    Column3    Column4    Column5    Column6  \
count   6.000000   6.000000   6.000000   6.000000   6.000000   6.000000   
mean   17.500000  18.500000  19.500000  20.500000  21.500000  22.500000   
std    13.095801  13.095801  13.095801  13.095801  13.095801  13.095801   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%     8.750000   9.750000  10.750000  11.750000  12.750000  13.750000   
50%    17.500000  18.500000  19.500000  20.500000  21.500000  22.500000   
75%    26.250000  27.250000  28.250000  29.250000  30.250000  31.250000   
max    35.000000  36.000000  37.000000  38.000000  39.000000  40.000000   

         Column7  
count   6.000000  
mean   23.500000  
std    13.095801  
min     6.000000  
25%    14.750000  
50%    23.500000  
75%    32.250000  
max    41.000000

In [15]:
# column name
type(df['Column1'])

pandas.core.series.Series

In [18]:
# Create new database just column  
df[['Column1','Column2','Column3']]

Column1  Column2  Column3
Row1        0        1        2
Row2        7        8        9
Row3       14       15       16
Row4       21       22       23
Row5       28       29       30
Row6       35       36       37

In [19]:
# using row index name loc
df.loc[['Row3','Row4']]

Column1  Column2  Column3  Column4  Column5  Column6  Column7
Row3       14       15       16       17       18       19       20
Row4       21       22       23       24       25       26       27

In [20]:
# using iloc function 
df.iloc[2:4,0:2]

Column1  Column2
Row3       14       15
Row4       21       22

In [21]:
# convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13],
       [15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27],
       [29, 30, 31, 32, 33, 34],
       [36, 37, 38, 39, 40, 41]])

In [22]:
# null operations
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
Column5    0
Column6    0
Column7    0
dtype: int64

In [26]:
# create a dataframe with null value 
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1","Row2"],
                columns=["Column1","Column2","Column3"])
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [ ]:
# checking there is null value or not 
df.isnull().sum()

In [28]:
# check in bool type 
df.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

### CSV File

In [30]:
# Reading Different Data sources with the help of pandas
from io import StringIO

In [31]:
# Read csv type file 
import pandas as pd
df=pd.read_csv('mercedesbenz.csv')
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [35]:
# Create csv type database 
data=('col_1,col_2,col_3\n'
     'x,y,1\n'
     'a,b,2\n'
     'c,d,3')
print(type(data))

<class 'str'>


In [36]:
# create in memory fill format object 
StringIO(data)

In [37]:
# then create database 
pd.read_csv(StringIO(data))

col_1 col_2  col_3
0     x     y      1
1     a     b      2
2     c     d      3

In [39]:
# read specific column
pd.read_csv(StringIO(data),usecols=['col_1','col_2'])

col_1 col_2
0     x     y
1     a     b
2     c     d

In [40]:
# with with first fice column 
import pandas as pd
df=pd.read_csv('mercedesbenz.csv',usecols=['X0','X1','X2','X3','X4','X5'])
df.head()

X0 X1  X2 X3 X4 X5
0   k  v  at  a  d  u
1   k  t  av  e  d  y
2  az  w   n  c  d  x
3  az  t   n  f  d  x
4  az  v   n  f  d  h

In [41]:
# from this database to csv file 
df.to_csv("Test.csv")

In [43]:
# datatype in csv 
data=('col_1,col_2,col_3,col_4\n'
     '1,2,3,4\n'
     '5,6,7,8\n'
     '9,10,11')
df = pd.read_csv(StringIO(data))
df

col_1  col_2  col_3  col_4
0      1      2      3    4.0
1      5      6      7    8.0
2      9     10     11    NaN

In [44]:
# check the info 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col_1   3 non-null      int64  
 1   col_2   3 non-null      int64  
 2   col_3   3 non-null      int64  
 3   col_4   2 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 228.0 bytes


In [46]:
# check null
df.isnull().sum()

col_1    0
col_2    0
col_3    0
col_4    1
dtype: int64

In [47]:
# check type to object 
df = pd.read_csv(StringIO(data),dtype="object")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col_1   3 non-null      object
 1   col_2   3 non-null      object
 2   col_3   3 non-null      object
 3   col_4   2 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes


In [48]:
# datatypes in csv
data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')

df=pd.read_csv(StringIO(data),dtype={'a':int,'b':float,'c':int})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int32  
 1   b       3 non-null      float64
 2   c       3 non-null      int32  
 3   d       2 non-null      float64
dtypes: float64(2), int32(2)
memory usage: 204.0 bytes


In [50]:
# useing index column 
data = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')
pd.read_csv(StringIO(data),index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [52]:
# this link is removed by owner.
# it is basically teb seperated value 
pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',sep='\t')  

HTTPError: HTTP Error 403: Forbidden

### Json File 

In [68]:
# json type data
j_data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'

In [71]:
type(j_data)

str

In [72]:
pd.read_json(j_data)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_916\2067471086.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(j_data)


employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [75]:
pd.read_json(j_data, orient='records')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_916\1922582182.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(j_data, orient='records')


employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [76]:
pd.read_json(j_data, orient='index')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_916\1070675698.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(j_data, orient='index')


0
employee_name                                              James
email                                            james@gmail.com
job_profile    [{'title1': 'Team Lead', 'title2': 'Sr. Develo...

In [104]:
# create another json type dataset 
import pandas as pd
df = pd.DataFrame([['a', 'b'], ['c', 'd']],
                  index=['row 1', 'row 2'],
                  columns=['col 1', 'col 2'])

In [105]:
df

col 1 col 2
row 1     a     b
row 2     c     d

In [106]:
# how data are converted into json 
df.to_json()

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [107]:
# as per index 
df.to_json(orient='index')

'{"row 1":{"col 1":"a","col 2":"b"},"row 2":{"col 1":"c","col 2":"d"}}'

In [108]:
# as per column
df.to_json(orient='columns')

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [109]:
# as per records 
df.to_json(orient='records')

'[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'

In [110]:
# as per split 
df.to_json(orient='split')

'{"columns":["col 1","col 2"],"index":["row 1","row 2"],"data":[["a","b"],["c","d"]]}'

In [111]:
# as per taable
df.to_json(orient='table')

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col 1","type":"string"},{"name":"col 2","type":"string"}],"primaryKey":["index"],"pandas_version":"1.4.0"},"data":[{"index":"row 1","col 1":"a","col 2":"b"},{"index":"row 2","col 1":"c","col 2":"d"}]}'

In [112]:
# convert it into jeson 
schema='{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col 1","type":"string"},{"name":"col 2","type":"string"}],"primaryKey":["index"],"pandas_version":"0.20.0"},"data":[{"index":"row 1","col 1":"a","col 2":"b"},{"index":"row 2","col 1":"c","col 2":"d"}]}'

In [113]:
pd.read_json(schema,orient='table')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_916\3334002861.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(schema,orient='table')


col 1 col 2
row 1     a     b
row 2     c     d

In [114]:
# csv to json file 
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)

In [115]:
# lets check the value 
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [116]:
# convert into json 
df.to_json(orient='index')

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3

In [117]:
# json type data
js_data = [{"employee_name": "James", "email": "james@gmail.com", "job_profile": {"title1":"Team Lead", "title2":"Sr. Developer"}}]

In [93]:
type(js_data)

list

In [97]:
pd.json_normalize(js_data)

employee_name            email job_profile.title1 job_profile.title2
0         James  james@gmail.com          Team Lead      Sr. Developer

In [120]:
data = [
    {
        "id": 1,
        "name": "Cole Volk",
        "fitness": {"height": 130, "weight": 60},
    },
    {"name": "Mark Reg", "fitness": {"height": 130, "weight": 60}},
    {
        "id": 2,
        "name": "Faye Raker",
        "fitness": {"height": 130, "weight": 60},
    },
]

In [121]:
# this normalized function create two seperate file of nested dict
pd.json_normalize(data)

id        name  fitness.height  fitness.weight
0  1.0   Cole Volk             130              60
1  NaN    Mark Reg             130              60
2  2.0  Faye Raker             130              60

In [100]:
# max level=0 means it will go just one level 
pd.json_normalize(data,max_level=0)

id        name                        fitness
0  1.0   Cole Volk  {'height': 130, 'weight': 60}
1  NaN    Mark Reg  {'height': 130, 'weight': 60}
2  2.0  Faye Raker  {'height': 130, 'weight': 60}

In [123]:
# max level=0 means it will go just one level 
pd.json_normalize(data,max_level=1)

id        name  fitness.height  fitness.weight
0  1.0   Cole Volk             130              60
1  NaN    Mark Reg             130              60
2  2.0  Faye Raker             130              60

In [124]:
data = [
    {
        "state": "Florida",
        "shortname": "FL",
        "info": {"governor": "Rick Scott"},
        "counties": [
            {"name": "Dade", "population": 12345},
            {"name": "Broward", "population": 40000},
            {"name": "Palm Beach", "population": 60000},
        ],
    },
    {
        "state": "Ohio",
        "shortname": "OH",
        "info": {"governor": "John Kasich"},
        "counties": [
            {"name": "Summit", "population": 1234},
            {"name": "Cuyahoga", "population": 1337},
        ],
    },
]

In [125]:
pd.json_normalize(data)

state shortname                                           counties  \
0  Florida        FL  [{'name': 'Dade', 'population': 12345}, {'name...   
1     Ohio        OH  [{'name': 'Summit', 'population': 1234}, {'nam...   

  info.governor  
0    Rick Scott  
1   John Kasich

In [126]:
# as countries are nested then we have to said it properly
pd.json_normalize(data, "counties",["state", "shortname",["info",'governor']])

name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

### HTML 

In [132]:
pip install lxml

Note: you may need to restart the kernel to use updated packages.
  Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/c3/b5/91c2249bfac02ee514ab135e9304b89d55967be7e53e94a879b74eec7a5c/lxml-5.3.0-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB 320.0 kB/s eta 0:00:12
    --------------------------------------- 0.1/3.8 MB 372.4 kB/s eta 0:00:11
   - -------------------------------------- 0.1/3.8 MB 717.5 kB/s eta 0:00:06
   -- ------------------------------------- 0.2/3.8 MB 958.4 kB/s eta 0:00:04
   -- ------------------------------------- 0.2/3.8 MB 1.2 MB/s eta 0:00:04
   ----- ---------------------------------- 0.5/3.8 MB 1.8 MB/s eta 0:00:02
   ------- -------------------------------- 0.7/3.8 MB 1.9 MB/s eta 0:00:02
   ---------- ----------------------------- 1.0/3.8 MB


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [133]:
# read html file 
html=pd.read_html("https://en.wikipedia.org/wiki/Mobile_country_code")

In [134]:
# show the type
type(html)

list

In [135]:
# this is the first table of this page 
html[0]

MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any   
1    1    1  TEST  Test network  Operational         any   
2  999   99   NaN  Internal use  Operational         any   
3  999  999   NaN  Internal use  Operational         any   

                              References and notes  
0                                              NaN  
1                                              NaN  
2  Internal use in private networks, no roaming[6]  
3  Internal use in private networks, no roaming[6]

In [136]:
# how to read the specific table
html=pd.read_html("https://en.wikipedia.org/wiki/Economy_of_the_United_States",match="Government debt")

In [137]:
print(type(html))
print(type(html[0]))

<class 'list'>
<class 'pandas.core.frame.DataFrame'>


In [140]:
html[1]

Year  GDP (in Bil. US$PPP)  GDP per capita (in US$ PPP)  \
0   1980                2857.3                      12552.9   
1   1981                3207.0                      13948.7   
2   1982                3343.8                      14405.0   
3   1983                3634.0                      15513.7   
4   1984                4037.7                      17086.4   
5   1985                4339.0                      18199.3   
6   1986                4579.6                      19034.8   
7   1987                4855.3                      20001.0   
8   1988                5236.4                      21376.0   
9   1989                5641.6                      22814.1   
10  1990                5963.1                      23848.0   
11  1991                6158.1                      24302.8   
12  1992                6520.3                      25392.9   
13  1993                6858.6                      26364.2   
14  1994                7287.3                      27674.0   
15  1995                7639.8                      28671.5   
16  1996                8073.1                      29947.0   
17  1997                8577.6                      31440.1   
18  1998                9062.8                      32833.7   
19  1999                9631.2                      34496.2   
20  2000               10251.0                      36312.8   
21  2001               10581.9                      37101.5   
22  2002               10929.1                      37945.8   
23  2003               11456.5                      39405.4   
24  2004               12217.2                      41641.6   
25  2005               13039.2                      44034.3   
26  2006               13815.6                      46216.9   
27  2007               14474.3                      47943.4   
28  2008               14769.9                      48470.6   
29  2009               14478.1                      47102.4   
30  2010               15049.0                      48586.3   
31  2011               15599.7                      50008.1   
32  2012               16254.0                      51736.7   
33  2013               16880.6                      53363.9   
34  2014               17608.1                      55263.8   
35  2015               18295.0                      57006.9   
36  2016               18804.9                      58179.6   
37  2017               19612.1                      60292.9   
38  2018               20656.5                      63165.2   
39  2019               21521.4                      65504.7   
40  2020               21322.9                      64367.4   
41  2021               23594.0                      70995.7   
42  2022               25744.1                      77191.8   
43  2023               27357.8                      81632.2   
44  2024               28781.0                      85372.6   
45  2025               29839.6                      87978.4   
46  2026               31018.7                      90902.7   
47  2027               32274.4                      94011.7   
48  2028               33582.2                      97230.6   

    GDP (in Bil. US$nominal)  GDP per capita (in US$ nominal)  \
0                     2857.3                          12552.9   
1                     3207.0                          13948.7   
2                     3343.8                          14405.0   
3                     3634.0                          15513.7   
4                     4037.7                          17086.4   
5                     4339.0                          18199.3   
6                     4579.6                          19034.8   
7                     4855.3                          20001.0   
8                     5236.4                          21376.0   
9                     5641.6                          22814.1   
10                    5963.1                          23848.0   
11                    6158.1                          24302.8   
12      

In [141]:
html=pd.read_html("https://en.wikipedia.org/wiki/Minnesota",match="Average daily maximum and minimum temperatures for selected cities in Minnesota")

In [142]:
html[0]

Location July (°F) July (°C) January (°F) January (°C)
0          Minneapolis     83/64     28/18         23/7       −4/−13
1           Saint Paul     83/63     28/17         23/6       −5/−14
2            Rochester     82/63     28/17         23/3       −5/−16
3               Duluth     76/55     24/13         19/1       −7/−17
4            St. Cloud     81/58     27/14        18/−1       −7/−18
5              Mankato     86/62     30/16         23/3       −5/−16
6  International Falls     77/52     25/11        15/−6       −9/−21

In [143]:
type(html[0])

pandas.core.frame.DataFrame

In [144]:
html[0].to_html('demo.html')

### XML 

In [145]:
# read xml file 
pd.read_xml("test.xml")

shape  degrees  sides
0    square      360    4.0
1    circle      360    NaN
2  triangle      180    3.0

In [148]:
# row xml data
xml = '''<?xml version='1.0' encoding='utf-8'?>
<data xmlns="http://example.com">
 <row>
   <shape>square</shape>
   <degrees>360</degrees>
   <sides>4.0</sides>
   <firstname>samman</firstname>
 </row>
 <row>
   <shape>circle</shape>
   <degrees>360</degrees>
   <sides/>
   <firstname/>
 </row>
 <row>
   <shape>triangle</shape>
   <degrees>180</degrees>
   <sides>3.0</sides>
   <firstname/>
 </row>
</data>'''

In [149]:
# read string type xml file 
pd.read_xml(xml)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_916\2704978085.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(xml)


shape  degrees  sides firstname
0    square      360    4.0    samman
1    circle      360    NaN      None
2  triangle      180    3.0      None

In [154]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<data>
  <row shape="square" degrees="360" sides="4.0" firstname="samman"/>
  <row shape="circle" degrees="360"/>
  <row shape="triangle" degrees="180" sides="3.0" lastname="abu salaho"/>
</data>'''

In [155]:
pd.read_xml(xml)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_916\2704978085.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(xml)


shape  degrees  sides firstname    lastname
0    square      360    4.0    samman        None
1    circle      360    NaN      None        None
2  triangle      180    3.0      None  abu salaho

In [156]:
xml = '''<?xml version='1.0' encoding='utf-8'?>
<doc:data xmlns:doc="https://example.com">
  <doc:row>
    <doc:shape>square</doc:shape>
    <doc:degrees>360</doc:degrees>
    <doc:sides>4.0</doc:sides>
  </doc:row>
  <doc:row>
    <doc:shape>circle</doc:shape>
    <doc:degrees>360</doc:degrees>
    <doc:sides/>
  </doc:row>
  <doc:row>
    <doc:shape>triangle</doc:shape>
    <doc:degrees>180</doc:degrees>
    <doc:sides>3.0</doc:sides>
  </doc:row>
</doc:data>'''

In [157]:
df=pd.read_xml(xml,xpath=".//doc:row",namespaces={"doc": "https://example.com"})

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_916\1616642587.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_xml(xml,xpath=".//doc:row",namespaces={"doc": "https://example.com"})


In [159]:
df.to_xml('newtest.xml')