In [ ]:
'''
tf.add() do element wise addition.
It can be add list tuple scaler
tf.constant/Variable/placeholder do this operration
with each other and with scaler and with list
and tuple

+ operator can be used to add two tensor
'''

import tensorflow as tf
import numpy as np

In [ ]:
# Scaler adding
a = 10
b = 20

c = a+b
c

30

In [ ]:
tf.add(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]

tf.add(l1, l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [ ]:
# add function with tuple
t1 = (1, 2, 3, 4)
t2 = (5, 6, 7, 8)

tf.add(t1, t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [ ]:
# if there are signle variable then we can add
# or either same kind of list or tuple
l1 = [1, 2, 3, 4]
a = 10

tf.add(l1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [ ]:
# we can do add function with numpy array

npa1 = np.array([1, 2, 3, 4, 5])
npa2 = np.array([6, 7, 8, 9, 1])

tf.add(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 7,  9, 11, 13,  6])>

In [ ]:
# numpy array with scaler value

npa1 = np.array([1, 2, 3, 4, 5])
npa2 = 10

tf.add(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([11, 12, 13, 14, 15])>

In [ ]:
npa1 = np.array([1, 2, 3, 4, 5])
npa2 = np.array([6])

tf.add(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 7,  8,  9, 10, 11])>

In [ ]:
# add operation with constant
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = tf.constant([1, 2, 3, 4, 5])

tf.add(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10], dtype=int32)>

In [ ]:
# add operation with constant with singlw value
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = tf.constant([1])

tf.add(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
# add operation with constant
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = 10

tf.add(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([11, 12, 13, 14, 15], dtype=int32)>

In [ ]:
# add operation with Varriable
tv1 = tf.Variable([1, 2, 3, 4, 5])
tv2 = tf.Variable([1, 2, 3, 4, 5])

tf.add(tv1, tv2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10], dtype=int32)>

In [ ]:
'''
Add two numpy array with different shape
Here the actual value is in the shape
compromise the max one will be the shape
of output

here the output shape is (2, 2, 3, 3)
'''
x = np.ones(6).reshape(1, 2, 1, 3)
x

y = np.ones(6).reshape(2, 1, 3, 1)
y

tf.add(x, y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]],


       [[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]]])>

In [18]:
tf.add(x, y).shape.as_list()

[2, 2, 3, 3]

In [19]:
# Scaler substract
a = 10
b = 20

c = a-b
c

-10

In [20]:
tf.subtract(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [21]:
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]

tf.subtract(l1, l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-4, -4, -4, -4], dtype=int32)>

In [22]:
# subtract function with tuple
t1 = (1, 2, 3, 4)
t2 = (5, 6, 7, 8)

tf.subtract(t1, t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-4, -4, -4, -4], dtype=int32)>

In [23]:
l1 = [1, 2, 3, 4]
a = 10

tf.subtract(l1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-9, -8, -7, -6], dtype=int32)>

In [24]:
npa1 = np.array([1, 2, 3, 4, 5])
npa2 = np.array([6])

tf.subtract(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([-5, -4, -3, -2, -1])>

In [25]:
# numpy array with scaler value

npa1 = np.array([1, 2, 3, 4, 5])
npa2 = 10

tf.add(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([11, 12, 13, 14, 15])>

In [26]:
# subtract operation with constant
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = tf.constant([1, 2, 3, 4, 5])

tf.subtract(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 0], dtype=int32)>

In [28]:
# subtract operation with constant with singlw value
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = tf.constant([1])

tf.subtract(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [30]:
# subtract operation with constant with singlw value
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = 10

tf.subtract(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-9, -8, -7, -6, -5], dtype=int32)>

In [31]:
# subtract operation with variable
tc1 = tf.Variable([1, 2, 3, 4, 5])
tc2 = tf.Variable([1, 2, 3, 4, 5])

tf.subtract(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 0], dtype=int32)>

In [32]:
# subtract operation with variable
tc1 = tf.Variable([1, 2, 3, 4, 5])
tc2 = tf.Variable([1])

tf.subtract(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [33]:
# subtract operation with variable
tc1 = tf.Variable([1, 2, 3, 4, 5])
tc2 = 10

tf.subtract(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-9, -8, -7, -6, -5], dtype=int32)>

In [34]:
'''
here the output will be the same
between the two shape size
'''

x = np.ones(6).reshape(1, 2, 1, 3)
x

y = np.ones(6).reshape(2, 1, 3, 1)
y

tf.subtract(x, y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])>