In [1]:
'''
Element wise power calculation
It can be given power to scaler or numpy array
It allow tf constant/variable/placeholder/sparse_matrix with specefic datatype

Dont pass data into int format, it will through error
'''
import tensorflow as tf
import numpy as np

In [2]:
a = 2
b = 4

tf.pow(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [3]:
# power of numpy array
arr = np.array([1, 2, 3, 4, 5], dtype = np.float32)
tf.pow(arr, 2)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25.], dtype=float32)>

In [6]:
# we can also do element wise power enitialization
# here shape must be same
arr = np.array([1, 2, 3, ], dtype = np.float64)
arr2 = np.array([2, 3, 2 ], dtype = np.float64)

tf.pow(arr, arr2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 8., 9.])>

In [7]:
tf.pow(tf.convert_to_tensor([1, 2, 3, 4], dtype = "float"), 2)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4.,  9., 16.], dtype=float32)>

In [11]:
# tensorflow with constant
tc1 = tf.constant([1, 2, 3, 4], dtype="float")
tc2 = tf.constant([1, 2, 3, 4], dtype="float")
tc3 = tf.constant([2], dtype="float")

a = tf.pow(tc1, 2)
print(a)

b = tf.pow(tc1, tc2)
print(b)

c = tf.pow(tc1, tc3)
print(c)

tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)
tf.Tensor([  1.   4.  27. 256.], shape=(4,), dtype=float32)
tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)


In [12]:
# tensorflow with Variable
tc1 = tf.Variable([1, 2, 3, 4], dtype="float")
tc2 = tf.Variable([1, 2, 3, 4], dtype="float")
tc3 = tf.Variable([2], dtype="float")

a = tf.pow(tc1, 2)
print(a)

b = tf.pow(tc1, tc2)
print(b)

c = tf.pow(tc1, tc3)
print(c)

tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)
tf.Tensor([  1.   4.  27. 256.], shape=(4,), dtype=float32)
tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)


In [13]:
# Maximum value of scaler

a = 10
b = 20

tf.maximum(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [14]:
tf.maximum(a, b).numpy()

20

In [15]:
# It will be done by elementwise
l1 = [10, 12, 13, 20]
l2 = [24, 8, 12, 18]

tf.maximum(l1, l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([24, 12, 13, 20], dtype=int32)>

In [17]:
# It will be done by elementwise
l1 = [10, 12, 13, 20]
a = 15

tf.maximum(l1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([15, 15, 15, 20], dtype=int32)>

In [18]:
# Compare two values with two array

arr1 = np.array([10, 12, 15, 17])
arr2 = np.array([12, 10, 17, 15])

arr = tf.maximum(arr1, arr2)

In [20]:
arr1 = np.array([1, 2, 3, 4])
arr2 = 3

tf.maximum(arr1, arr2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 3, 3, 4])>

In [21]:
# Compare two value with tensorflow constant
tf_ct1 = tf.constant([2, 2, 3, 8])
tf_ct2 = tf.constant([12, 1, 2, 5])

tf.maximum(tf_ct1, tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12,  2,  3,  8], dtype=int32)>

In [22]:
# Compare two value with tensorflow Variable
tf_ct1 = tf.Variable([2, 2, 3, 8])
tf_ct2 = tf.Variable([12, 1, 2, 5])

tf.maximum(tf_ct1, tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12,  2,  3,  8], dtype=int32)>

In [23]:
# we can also compare list with constant
tf_ct1 = tf.Variable([2, 2, 3, 8])
li = [12, 1, 2, 5]

tf.maximum(tf_ct1, li)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12,  2,  3,  8], dtype=int32)>