In [ ]:
'''
tf.multiply() do element wise multiplication.
It can be add list tuple scaler
tf.constant/Variable/placeholder do this operration
with each other and with scaler and with list
and tuple

* operator can be used to add two tensor
'''

import tensorflow as tf
import numpy as np

In [35]:
# Scaler adding
a = 10
b = 20

c = a*b
c

200

In [36]:
tf.multiply(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

In [37]:
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]

tf.multiply(l1, l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 12, 21, 32], dtype=int32)>

In [38]:
# add function with tuple
t1 = (1, 2, 3, 4)
t2 = (5, 6, 7, 8)

tf.multiply(t1, t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 12, 21, 32], dtype=int32)>

In [39]:
# if there are signle variable then we can multiply
# or either same kind of list or tuple
l1 = [1, 2, 3, 4]
a = 10

tf.multiply(l1, a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

In [40]:
# we can do multiply function with numpy array

npa1 = np.array([1, 2, 3, 4, 5])
npa2 = np.array([6, 7, 8, 9, 1])

tf.multiply(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 6, 14, 24, 36,  5])>

In [41]:
# numpy array with scaler value

npa1 = np.array([1, 2, 3, 4, 5])
npa2 = 10

tf.multiply(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([10, 20, 30, 40, 50])>

In [42]:
npa1 = np.array([1, 2, 3, 4, 5])
npa2 = np.array([6])

tf.multiply(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 6, 12, 18, 24, 30])>

In [43]:
# add operation with constant
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = tf.constant([1, 2, 3, 4, 5])

tf.multiply(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25], dtype=int32)>

In [44]:
# add operation with constant with singlw value
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = tf.constant([1])

tf.multiply(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [45]:
# add operation with constant
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = 10

tf.multiply(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50], dtype=int32)>

In [46]:
# add operation with Varriable
tv1 = tf.Variable([1, 2, 3, 4, 5])
tv2 = tf.Variable([1, 2, 3, 4, 5])

tf.multiply(tv1, tv2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25], dtype=int32)>

In [47]:
'''
Add two numpy array with different shape
Here the actual value is in the shape
compromise the max one will be the shape
of output

here the output shape is (2, 2, 3, 3)
'''
x = np.ones(6).reshape(1, 2, 1, 3)
x

y = np.ones(6).reshape(2, 1, 3, 1)
y

tf.multiply(x, y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])>

In [48]:
tf.multiply(x, y).shape.as_list()

[2, 2, 3, 3]

In [49]:
# Scaler division
a = 10
b = 20

c = a/b
c

0.5

In [50]:
tf.divide(a, b)

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

In [51]:
l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]

tf.divide(l1, l2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.2       , 0.33333333, 0.42857143, 0.5       ])>

In [52]:
# divide function with tuple
t1 = (1, 2, 3, 4)
t2 = (5, 6, 7, 8)

tf.divide(t1, t2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.2       , 0.33333333, 0.42857143, 0.5       ])>

In [53]:
l1 = [1, 2, 3, 4]
a = 10

tf.divide(l1, a)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.1, 0.2, 0.3, 0.4])>

In [54]:
npa1 = np.array([1, 2, 3, 4, 5])
npa2 = np.array([6])

tf.divide(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.16666667, 0.33333333, 0.5       , 0.66666667, 0.83333333])>

In [55]:
# numpy array with scaler value

npa1 = np.array([1, 2, 3, 4, 5])
npa2 = 10

tf.divide(npa1, npa2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.1, 0.2, 0.3, 0.4, 0.5])>

In [56]:
# divide operation with constant
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = tf.constant([1, 2, 3, 4, 5])

tf.divide(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 1., 1., 1., 1.])>

In [57]:
# divide operation with constant with singlw value
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = tf.constant([1])

tf.divide(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 2., 3., 4., 5.])>

In [58]:
# divide operation with constant with singlw value
tc1 = tf.constant([1, 2, 3, 4, 5])
tc2 = 10

tf.divide(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.1, 0.2, 0.3, 0.4, 0.5])>

In [59]:
# divide operation with variable
tc1 = tf.Variable([1, 2, 3, 4, 5])
tc2 = tf.Variable([1, 2, 3, 4, 5])

tf.divide(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 1., 1., 1., 1.])>

In [60]:
# divide operation with variable
tc1 = tf.Variable([1, 2, 3, 4, 5])
tc2 = tf.Variable([1])

tf.divide(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 2., 3., 4., 5.])>

In [61]:
# divide operation with variable
tc1 = tf.Variable([1, 2, 3, 4, 5])
tc2 = 10

tf.divide(tc1, tc2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.1, 0.2, 0.3, 0.4, 0.5])>

In [62]:
'''
here the output will be the same
between the two shape size
'''

x = np.ones(6).reshape(1, 2, 1, 3)
x

y = np.ones(6).reshape(2, 1, 3, 1)
y

tf.divide(x, y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])>