In [1]:
'''
Element wise power calculation
It can be given power to scaler or numpy array
It allow tf constant/variable/placeholder/sparse_matrix with specefic datatype

Dont pass data into int format, it will through error
'''
import tensorflow as tf
import numpy as np

In [2]:
a = 2
b = 4

tf.pow(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [3]:
# power of numpy array
arr = np.array([1, 2, 3, 4, 5], dtype = np.float32)
tf.pow(arr, 2)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25.], dtype=float32)>

In [6]:
# we can also do element wise power enitialization
# here shape must be same
arr = np.array([1, 2, 3, ], dtype = np.float64)
arr2 = np.array([2, 3, 2 ], dtype = np.float64)

tf.pow(arr, arr2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 8., 9.])>

In [7]:
tf.pow(tf.convert_to_tensor([1, 2, 3, 4], dtype = "float"), 2)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4.,  9., 16.], dtype=float32)>

In [11]:
# tensorflow with constant
tc1 = tf.constant([1, 2, 3, 4], dtype="float")
tc2 = tf.constant([1, 2, 3, 4], dtype="float")
tc3 = tf.constant([2], dtype="float")

a = tf.pow(tc1, 2)
print(a)

b = tf.pow(tc1, tc2)
print(b)

c = tf.pow(tc1, tc3)
print(c)

tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)
tf.Tensor([  1.   4.  27. 256.], shape=(4,), dtype=float32)
tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)


In [12]:
# tensorflow with Variable
tc1 = tf.Variable([1, 2, 3, 4], dtype="float")
tc2 = tf.Variable([1, 2, 3, 4], dtype="float")
tc3 = tf.Variable([2], dtype="float")

a = tf.pow(tc1, 2)
print(a)

b = tf.pow(tc1, tc2)
print(b)

c = tf.pow(tc1, tc3)
print(c)

tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)
tf.Tensor([  1.   4.  27. 256.], shape=(4,), dtype=float32)
tf.Tensor([ 1.  4.  9. 16.], shape=(4,), dtype=float32)
