In [2]:
import tensorflow as tf
import numpy as np

In [3]:
'''
Sprace Tensor --> tensor that conitain mostly zero values are called sparce tensor
Dense Tensor --> tensor that cointain mostly one value are called dense tensor

Sparse tensor enable efficient storage and processing of tensors that contain
a lot of zero values it used extensively in encoding schene like tf-idf in nlp
and for preprocess images with a lot of dark pixel in computer vision.

Currently sparse tensors in tensorflow are encoded using the co-ordinate
list format(coo)

values: A 1D tensor with shape[N] containing all non_zero values
indices: A 2D tensor with shape [N, Rank] containing the indices of nonzero values
dense_shape: A 1D tensor with shape [N], specefying the shape of the tensor

Non_Zero value in the context of sparce tensor is a valur that not explicitely encoded

syntex

tf.Sparse.SparseTensor(indices, values, dense_shape)
'''

# create tensorflow sparse matrix
st1 = tf.SparseTensor(indices = [[1, 2], [3, 4]], values = [10, 20], dense_shape =[3, 10])
st1

SparseTensor(indices=tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

In [4]:
# Create an array
arr = np.array([[1, 0, 0, 0],
                [0, 0, 0, 0],
                [0, 0, 2, 0],
                [0, 0, 0, 4]])
print(arr)

[[1 0 0 0]
 [0 0 0 0]
 [0 0 2 0]
 [0 0 0 4]]


In [7]:
# Create sparse from dense
sp2 = tf.sparse.from_dense(arr)
sp2

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 4], shape=(3,), dtype=int64), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

In [10]:
# show the value
sp2.values

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 4])>

In [11]:
# show the indices
sp2.indices

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[0, 0],
       [2, 2],
       [3, 3]])>

In [13]:
# show dense_shape as a list
sp2.dense_shape.numpy().tolist()

[4, 4]

In [14]:
# sparse to dense tensor
dns = tf.sparse.to_dense(sp2)
dns

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])>

In [15]:
# In numpy format
dns.numpy()

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

In [17]:
# mathmatical operation on sparse tensor
'''
In this function we have to give to sparse matrix with the same shape
the output will also generate in the sparse formet. But the best part is
it just add two values of sparse. Here the values for sp2 sparse is [1, 2, 4].
then same addition will be [2, 4, 8]. So computation here is much more eaiser
we dont have to calculate the whole matrix.
'''
sp_add = tf.sparse.add(sp2, sp2)
sp_add

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2 4 8], shape=(3,), dtype=int64), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

In [19]:
# lets see the dense format for this add value
dns2 = tf.sparse.to_dense(sp_add)
dns

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])>