In [ ]:
'''
tf.sqrt(): calculate element wise squere root
of numpy array and tf tensor. It can be give sqrt of
list, tuple, scaler

It allow tf variable/constant/placeholder/sparse matrix
with specific datatype
'''
import tensorflow as tf
import numpy as np

In [ ]:
a = 9.0
tf.sqrt(a)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [ ]:
# sqrt with list
l1 = [4.0, 9.0, 16.0]
tf.sqrt(l1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [ ]:
# sqrt with tuple
t1 = (4.0, 9.0, 16.0)
tf.sqrt(t1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [ ]:
npa1 = np.array([4, 9, 16], dtype=float)
tf.sqrt(npa1)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [ ]:
npa1.dtype

dtype('float64')

In [ ]:
y = np.ones(6).reshape(1, 3, 1, 2)*4
tf.sqrt(y)

<tf.Tensor: shape=(1, 3, 1, 2), dtype=float64, numpy=
array([[[[2., 2.]],

        [[2., 2.]],

        [[2., 2.]]]])>

In [ ]:
# Sqere root of tensor
tf.sqrt(tf.convert_to_tensor(4, dtype='float'))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [ ]:
tf.sqrt(tf.convert_to_tensor([1, 2, 3, 4], dtype='float'))

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508, 2.       ], dtype=float32)>

In [ ]:
# squere root of TF constant tensor
tf_ct = tf.constant([4, 9, 16], dtype='float')
tf.sqrt(tf_ct)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>