In [1]:
import tensorflow as tf
import numpy as np

In [2]:
'''
In TensorFlow 1.x, placeholders were used as empty spots in the code where data would
be fed in later, allowing flexibility for changing inputs.

They were defined with tf.placeholder and filled with data when running the model.
In TensorFlow 2.x, placeholders were removed, making it easier to handle data
directly with standard Python functions and datasets

# It allowys us to careate our operations and build our computation graph
without using data

In TensorFlow 1.x, the code was
tf.placeholder(dtype=tf.float32, shape=(400*400))
'''

'\nIn TensorFlow 1.x, placeholders were used as empty spots in the code where data would\nbe fed in later, allowing flexibility for changing inputs.\n\nThey were defined with tf.placeholder and filled with data when running the model. \nIn TensorFlow 2.x, placeholders were removed, making it easier to handle data\ndirectly with standard Python functions and datasets\n\n# It allowys us to careate our operations and build our computation graph\nwithout using data\n\nIn TensorFlow 1.x, the code was \ntf.placeholder(dtype=tf.float32, shape=(400*400))\n'

In [3]:
'''
With eager execution disabled, TensorFlow behaves more like it did in version 1.x,
allowing the use of placeholders, sessions, and computational graphs. However,
it’s generally recommended to use newer data-handling techniques in TensorFlow 2.x
for better compatibility and easier debugging.
'''
tf.compat.v1.disable_eager_execution()

In [4]:
# Create two placeholder
a = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))
print(a)
b = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))
print(b)

Tensor("Placeholder:0", shape=(400, 400), dtype=float32)
Tensor("Placeholder_1:0", shape=(400, 400), dtype=float32)


In [5]:
# Perform mathtatical operation with tensor flow
c = tf.add(a, b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

In [6]:
# create ones array with shape 400*400
ones_array = np.ones((400,400), np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [7]:
# Execute tensorflow placeholder using session

with tf.compat.v1.Session() as sess:
  d = sess.run(c, feed_dict={a:ones_array, b:ones_array})

In [8]:
print(d)

[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
