In [1]:
!pip install tensorflow

In [6]:
# import tensorflow
import tensorflow as tf
import numpy as np

In [3]:
# show the version
tf.__version__

'2.17.0'

In [4]:
# show to see gpu is available or not
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [5]:
# constant varriable in tensorflow
a = tf.constant(10)
print(a)

b = tf.constant(12.25)
print(b)

c = tf.constant('a')
print(c)

d = tf.constant("My name is abu salaho as samman")
print(d)

e = tf.constant(False)
print(c)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(12.25, shape=(), dtype=float32)
tf.Tensor(b'a', shape=(), dtype=string)
tf.Tensor(b'My name is abu salaho as samman', shape=(), dtype=string)
tf.Tensor(b'a', shape=(), dtype=string)


In [7]:
# create array using tensorflow
np_array = tf.constant(np.array([1, 2, 3, 4, 5]))
np_array

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

In [8]:
arr_2d = tf.constant([[1, 2],[3, 4]])
arr_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [9]:
arr = tf.constant([1, 2, 4, 5], shape=(2,2), dtype="int32")
arr

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [10]:
arr_d = tf.constant([[[1, 2], [3, 4]]], dtype="float32")
arr_d

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.]]], dtype=float32)>

In [11]:
type(np_array)

tensorflow.python.framework.ops.EagerTensor

In [15]:
arr_2d.shape

TensorShape([2, 2])

In [16]:
arr_2d.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [18]:
arr_2d.numpy()[0,1]

2

In [20]:
'''
The error "Can't convert Python sequence with mixed types to Tensor like list"
occurs because tensors require elements of the same data type,
but your list contains mixed data types.
'''
#--> tf.constant([1, 2.5,'samman'])

# Example list with mixed types
mixed_list = [1, 2.0, '3', 4]

# Convert elements to float
uniform_list = [float(x) for x in mixed_list]
arr = tf.constant(uniform_list)
arr

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>