In [1]:
# importing library

import tensorflow as tf
import numpy as np

In [2]:
'''
In TensorFlow, a Variable is a mutable tensor used to store parameters
that can change during model training, such as weights in neural networks.
Unlike constants, Variables are updated by backpropagation and
optimized to minimize loss.

After constraction the shape and datatype can change but value can be
changed only by assign method

where variable name is 0, shape is 1
'''
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [3]:
# different Properties of Variable
a = tf.Variable([1, 2, 3, 4])
print(a.name)
print(a.shape)
print(a.dtype)
print(a.numpy)
print(type(a))

Variable:0
(4,)
<dtype: 'int32'>
<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [4]:
# We can create variable with different data type
tf_a = tf.Variable([1, 2.5, 4, 6.5])
print(tf_a)
tf_b = tf.Variable(['1', 'a', 'b', 'd'])
print(tf_b)
tf_c = tf.Variable([True, False])
print(tf_c)
tf_d = tf.Variable([4 + 3j])
print(tf_d)

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1. , 2.5, 4. , 6.5], dtype=float32)>
<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'1', b'a', b'b', b'd'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>
<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([4.+3.j])>


In [5]:
# 2d variable in tensorflow
tf_2d = tf.Variable([[1, 2],[3, 4]], shape = (2, 2), dtype="float32")
tf_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [6]:
# 1D variable in tensorflow
td_1d = tf.Variable([1, 2, 3, 4], dtype="float32")
print(td_1d)

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>


In [7]:
'''
we can reshape after constact
But in constant we can not change any value
after constraction
'''
a = tf.reshape(td_1d, (2, 2))
print(a)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [8]:
# It will always show the index of highest value
tf.argmax(a)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [9]:
a = tf.Variable([1, 2, 3, 4])
print(a)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>


In [10]:
# convert to tensor
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [11]:
'''
here the datatype and shape should be same
and we change the previous Value
'''
a.assign([4, 5, 6, 7])
print(a)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>


In [12]:
'''
Assign variable to another memory
It will do add operation then save this value into another memory
'''
a.assign_add([4, 12, 3, 7])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 17,  9, 14], dtype=int32)>