In [47]:
import tensorflow as tf

In [48]:
x1 = tf.constant(4)
print(x1)

tf.Tensor(4, shape=(), dtype=int32)


In [49]:
x2 = tf.constant(4.0)
print(x2)

tf.Tensor(4.0, shape=(), dtype=float32)


In [50]:
x3 = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x3)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [51]:
x4 = tf.constant([[1, 2, 3],[4, 5, 6]])
print(x4)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [52]:
x = tf.ones((3, 3))
print(x)

x1 = tf.zeros((3, 3))
print(x1)

x2 = tf.eye(3)
print(x2)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [53]:
# normal distribution
x = tf.random.normal((3, 3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.32925582 -0.56235605  0.98049873]
 [ 0.5517517  -0.8436611   0.32703617]
 [ 0.25444657 -2.3478444  -0.04364091]], shape=(3, 3), dtype=float32)


In [54]:
# uniform distribution
y = tf.random.uniform((3,3),minval=0, maxval=1 )
print(y)

tf.Tensor(
[[0.34999442 0.9829545  0.39775527]
 [0.8939278  0.7409376  0.5064821 ]
 [0.05882049 0.4776559  0.12164366]], shape=(3, 3), dtype=float32)


In [55]:
tf.range(5)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [56]:
tf.range(start=3, limit=10, delta=2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 5, 7, 9], dtype=int32)>

In [57]:
x = tf.range(5)
x1 = tf.cast(x, dtype=tf.float32)
print(x1)

tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float32)


In [58]:
# Mathmatical operation
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z1 = tf.add(x, y)
z1 = x + y
print(z1)

z2 = tf.subtract(x, y)
z2 = x - y
print(z2)

z3 = tf.divide(x, y)
z3 = x / y
print(z3)

z4 = tf.multiply(x, y)
z4 = x * y
print(z4)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [59]:
# element with multiplication with sum
z = tf.tensordot(x, y, axes=1)
print(z) #(9*1)+(8*2)+(7*3)=46

tf.Tensor(46, shape=(), dtype=int32)


In [60]:
z =tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [61]:
z = x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [62]:
# Matrix multiplication
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

z = tf.matmul(x, y) # this two are same
z = x @ y
print(z)

tf.Tensor(
[[-0.6331503  -0.36920255  0.9924589  -1.6992702 ]
 [-0.15416397  0.40848094  0.31398597 -1.2653677 ]], shape=(2, 4), dtype=float32)


In [63]:
# indexcing
x = tf.constant([0, 1, 1, 2, 2, 3, 4, 4])
print(x[:])
print(x[1:3])
print(x[::2])
print(x[::-1])
print(x[1:5:2])

tf.Tensor([0 1 1 2 2 3 4 4], shape=(8,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 2 4], shape=(4,), dtype=int32)
tf.Tensor([4 4 3 2 2 1 1 0], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [64]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[0,1:3])
print(x[0:3,:1])

tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor(
[[1]
 [3]
 [5]], shape=(3, 1), dtype=int32)


In [65]:
# Reshaping
x = tf.range(9)
y =tf.reshape(x, (3,3))
print(y)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [68]:
y = tf.transpose(y, perm=[1,0])
print(y)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
